### ISSUE TITLE
Create an initial release

### ISSUE THREAD

**Issue by ThePixelDeveloper** [skymeyer/phpkafka-stubs#1]
Is it possible to create an initial release of the package so I don't have to rely on dev-master as a version string? 0.0.1 or something will allow me to use the package will allow me avoid changing my minimum stability flag.

-Mathew

**Comment by skymeyer** [comment]
Hi, seems I forgot to enable my notifications, hence my late answer. Will see to update this soon. There is an updated stub out too.

**Comment by skymeyer** [comment]
Done, updated to latest stubs as well.
